### PR TITLE
Fearure/1032

### PR DESCRIPTION
**Pull request by RomanGalochkin**
It loads the measurements on demand:
Screenshot_20200207_133144

#1032 
#1036

### CODE REVIEW

**Comment by OAGr** [comment]
Oh nice, happy to see this!

**Comment by OAGr** [comment]
Looks good, will merge after it passes.

**Comment by OAGr** [comment]
Seems to have failed, not sure why. I'm re-running.
image

**Comment by RomanGalochkin** [comment]
Yes, thanks, a minute.

**Pull request merged**
