### PR TITLE
Order leaderboard

### PR DESCRIPTION
**Pull request by NunoSempere**
Orders the leaderboards by Total Net Log Score.

order_leaderboard

### CODE REVIEW

**Comment by OAGr** [comment]
Nice, looks good.

One issue is that ideally this would probably be done on the server side instead; if there are more than 20 items, then I assume ordering won't hold between pages.

Happy to delay on that though.

**Comment by NunoSempere** [comment]
Just checked, it indeed doesn't preserve the ordering between pages.

**Comment by OAGr** [comment]
Would you want me to merge it without the backend change? It seems nice for a few items, but possible confusing. In general I don't like confusing.

**Comment by RomanGalochkin** [comment]
So why not, I think if it will be needed we implement this on the server-side.

**Comment by OAGr** [comment]
@RomanGalochkin how difficult would this be to do on the server side?

**Comment by RomanGalochkin** [comment]
Give me a minute.

**Comment by RomanGalochkin** [comment]
At this moment this feature will require some hours (more than 4) since this property is not stored in DB.

**Comment by OAGr** [comment]
Good to know. I don't think it's worth that much now, maybe later though.

**Comment by OAGr** [comment]
I'm going to close this, can reinspect when server change is implemented.

**Comment by NunoSempere** [comment]
Nothing against.

**Pull request closed without merging**
