### PR TITLE
Adds logger

### PR DESCRIPTION
**Pull request by RomanGalochkin**
First of all, we need to store logs in Google Services. Because on my local version this part of the application works as we expect.

### CODE REVIEW

**Comment by OAGr** [comment]
That works. That said, again, I'm not sure how important the Ken story is; it if takes more than another hour or so, I'd just stop and do something else.

**Comment by OAGr** [comment]
I'll write some more stories soon.

**Comment by OAGr** [comment]
I promoted everything on master to prod, so you should be able to debug this.

**Comment by RomanGalochkin** [comment]
Ok, thanks.

**Pull request merged**
