### PR TITLE
Feature/557 - leaderboard by question

### PR DESCRIPTION
**Pull request by RomanGalochkin**
#557 

Please, consider the PR after all previous are merged.

### CODE REVIEW

**Comment by OAGr** [comment]
Overall, looks good. There are some issues though (sorry if this wasn't obvious earlier)

1. Items should only show up on the "By Question" list if the agent made at least one prediction for that measurable, **and** that measurable was resolved. Otherwise, there's no score associated with it (yet).

2. Measurable-agent pairs should be unique. I'm seeing a lot of duplication for some reason. The pair exists to include all information about that grouping. 

image

**Comment by RomanGalochkin** [comment]
Ok, sure, will fix in 5 minutes

**Comment by RomanGalochkin** [comment]
Fixed.

**Comment by RomanGalochkin** [comment]
I feel that we should count Measurements if they are Competitive, Objective, Aggregation but not Comment? (predictionCountTotal)

**Comment by OAGr** [comment]
Hm... we should probably just count competitive + aggregation measurements.

**Comment by RomanGalochkin** [comment]
ok, will update

**Comment by OAGr** [comment]
Hm... just do in a different PR or something, want to get these other stories in.

**Comment by RomanGalochkin** [comment]
sure

**Pull request merged**
