### PR TITLE
Feature/549

### PR DESCRIPTION
**Pull request by RomanGalochkin**
#549

### CODE REVIEW

**Comment by OAGr** [comment]
Does this code actually return the actual measurementScoreSet? The code seems so simple, like the part of the logic to figure out what the outcome measurement and previousAggregate is missing.

**Comment by RomanGalochkin** [comment]
No, it does not return actual data. It is not obvious from the issue how it should work.

**Comment by OAGr** [comment]
Ok, I left comments in slack.

**Comment by RomanGalochkin** [comment]
Have updated this PR.

**Pull request merged**
